# Generated by Django 3.2 on 2022-11-30 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_id', models.PositiveIntegerField(unique=True)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=250, null=True)),
                ('summary', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='news/')),
                ('date_published', models.DateTimeField(null=True)),
                ('date_modified', models.DateTimeField(null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.author')),
            ],
        ),
    ]
