# Generated by Django 3.2 on 2022-11-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='new_id',
            field=models.PositiveIntegerField(),
        ),
    ]
